### ISSUE TITLE
fixed_libil2cpp.poko

### ISSUE THREAD

**Issue by sdssaeq** [Poko-Apps/CodMDumper#1]
what should i do , is it fine to delete(rename) .poko

**Comment by Poko-Apps** [comment]
It's just a temporary file ! After dumping the lib you can obviously rename it for further use or even delete it .

**Comment by sdssaeq** [comment]
thanks i think its like ur extension must use in another app

**Comment by sdssaeq** [comment]
i rename it and open it on ida pro works perfecly , i just afraid doing something thanks for the asnwer
