### ISSUE TITLE
Extansion file error

### ISSUE THREAD

**Issue by Dhanasekhar-EEE** [Poko-Apps/CodMDumper#3]
![Screenshot_20220706_132003](https://user-images.githubusercontent.com/60638679/177498721-f8242c85-eaee-4ebc-a0cf-47fd85060e3c.jpg)
Extansion file error.
Please fix this,
Please help me dump il2cpp.so of codm global.

**Comment by Poko-Apps** [comment]
Hello !!
You must not rename any file.
Rename the "Extansion.p0k0" back to "extansion.p0k0"

**Comment by Dhanasekhar-EEE** [comment]
> Hello !! You must not rename any file. Rename the "Extansion.p0k0" back to "extansion.p0k0"

thank you very much, finally got the dump.so
